//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "movie")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub release_date: Date,
    pub title: String,
    pub overview: String,
    #[sea_orm(column_type = "Float")]
    pub popularity: f32,
    pub genre: String,
    #[sea_orm(column_type = "Text")]
    pub poster_url: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::showtime::Entity")]
    Showtime,
}

impl Related<super::showtime::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Showtime.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
