//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9

pub use super::movie::Entity as Movie;
pub use super::room::Entity as Room;
pub use super::showtime::Entity as Showtime;
pub use super::showtime_room::Entity as ShowtimeRoom;
pub use super::taken_seat::Entity as TakenSeat;
pub use super::theater::Entity as Theater;
