//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "showtime")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub movie_id: Uuid,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::movie::Entity",
        from = "Column::MovieId",
        to = "super::movie::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Movie,
    #[sea_orm(has_many = "super::showtime_room::Entity")]
    ShowtimeRoom,
    #[sea_orm(has_many = "super::taken_seat::Entity")]
    TakenSeat,
}

impl Related<super::movie::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Movie.def()
    }
}

impl Related<super::showtime_room::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShowtimeRoom.def()
    }
}

impl Related<super::taken_seat::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TakenSeat.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
