//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "taken_seat")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub showtime_id: Uuid,
    pub showtime_room_id: i32,
    pub seat_identifier: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::showtime::Entity",
        from = "Column::ShowtimeId",
        to = "super::showtime::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Showtime,
    #[sea_orm(
        belongs_to = "super::showtime_room::Entity",
        from = "Column::ShowtimeRoomId",
        to = "super::showtime_room::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ShowtimeRoom,
}

impl Related<super::showtime::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Showtime.def()
    }
}

impl Related<super::showtime_room::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShowtimeRoom.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
